### ISSUE TITLE
installation..

### ISSUE THREAD

**Issue by dlroxe** [isb-cgc/examples-R#15]
The instructions say this:

install_github("isb-cgc", "examples-R", build_vignettes=TRUE)

That fails in my R studio:
///
> install_github("isb-cgc", "examples-R", build_vignettes=TRUE)
Downloading GitHub repo examples-R/isb-cgc@master
Error in download(dest, src, auth) : client error: (404) Not Found
In addition: Warning message:
Username parameter is deprecated. Please use examples-R/isb-cgc 
///

On the other hand, this seems to work (note transposition of first two arguments):

///
> install_github("examples-R", "isb-cgc", build_vignettes=TRUE)
Downloading GitHub repo isb-cgc/examples-R@master
...
///

PS

I wish I could see how to make a comment with ASCII line separators, ">" markers, etc. *without* markdown formatting.  Oh, well.

**Comment by Gibbsdavidl** [comment]
Thanks for letting us know! Fixed.
