### ISSUE TITLE
Missing images.

### ISSUE THREAD

**Issue by deflaux** [isb-cgc/examples-R#16]
Both of these are missing an image towards the bottom:
* https://github.com/isb-cgc/examples-R/blob/master/inst/doc/ExpressionandMethylationCorrelation.md
* https://github.com/isb-cgc/examples-R/blob/master/inst/doc/ExpressionandProteinCorrelation.md

The best way to fix is to give all Rmd chunks that generate an image a particular name.
```
 ```{r my image name, fig.align="center", fig.width=12, fig.height=12}
 ggplot(...)
```

**Comment by Gibbsdavidl** [comment]
Fixed the img links. Still need to update the Rmd chunk names.

**Comment by Gibbsdavidl** [comment]
It's fixed.
