### ISSUE TITLE
Could not find instructions for troubleshooting/reseting oauth2

### ISSUE THREAD

**Issue by bmbroom** [isb-cgc/examples-R#23]
I could not find the promised instructions for troubleshooting/reseting oauth2 in the link at the bottom of the README.  Can you provide a more direct pointer?

**Comment by bmbroom** [comment]
Sorry. Found it. Gray text on a grey background code blob.  Not what I was scanning for.  Perhaps add a header?

In any case, those instructions don't work. getOption("httr_oauth_cache") returns TRUE, which file.remove doesn't like.

I get the following error:
```
Auto-refreshing stale OAuth token.
Error: 
```
I don't see anything on-screen from the very brief 'Auto-refreshing' action and the error message is blank.

**Comment by Gibbsdavidl** [comment]
Did this get resolved?  A little heavy handed, but one thing that always works, is to delete the .httr-oauth directory, and re-authorize.

**Comment by bmbroom** [comment]
I killed my rstudio container and started a new one.  Excessively heavy handed!

Turns out oauth was (probably) working all along.   Actual problem was because of an incompatible version of httr package.  Originally it worked for me, so I think the incompatible package version was loaded automagically when I installed another package.
