### ISSUE TITLE
usage and arguments for list_cohorts inconsistent

### ISSUE THREAD

**Issue by vjcitn** [isb-cgc/examples-R#24]
output of ?list_cohorts (the 'arguments' description seems wrong)

List cohorts

Description:

     Using your auth token, get a list of saved cohorts

Usage:

     list_cohorts(a_token)
     
Arguments:

sample_barcode: A TCGA patient barcode like "TCGA-02-0001"

**Comment by pgrosu** [comment]
Hi Vince,

I believe the implementation actually uses a REST interface to get the list of cohorts associated with a given user, based on their Google access token.  Below is the R function that does this:

```R
list_cohorts <- function(a_token) {
	req <- GET("https://api-dot-isb-cgc.appspot.com/_ah/api/cohort_api/v1/cohorts_list", config(token = a_token))
	stop_for_status(req)
	content(req)
}
```

The above is listed in the following file:

https://github.com/isb-cgc/examples-R/blob/06503a0129b737631a2ea8fbf1e4e9cc4b4bfd25/R/api_interface.R#L150-154

Hope it helps,
~p

**Comment by vjcitn** [comment]
That sounds accurate for the code, but if you read the man page you see that the argument a_token is not documented, and an unused argument "sample_barcode" is presented in the man page.  It seems someone has copied an Rd template, changed the usage component but did not continue on to the "Arguments" segment.  Thanks, you can close this.

**Comment by pgrosu** [comment]
I also value documentation, so I think your point is still valid.  I was pointing to why that might have been there.  It probably would still be useful to add more documentation to the help page - I'm sure other users might interpret the help page the same way.  (I think only the creator of an issue, or the admins see the button to close an issue.)

**Comment by Gibbsdavidl** [comment]
Thanks for pointing that out!  I'll get it fixed.

**Comment by pgrosu** [comment]
Thank you David,

Paul
